### ISSUE TITLE
JS-error when editing calue in color-input

### ISSUE THREAD

**Issue by cmitz** [jeremejevs/trimless-gmail#32]
Hi, I'm getting this message in my console:
`TypeError: $(...).spectrum is not a function`

Is this a known issue? If not, please tell so I can provide more information.

**Comment by jeremejevs** [comment]
Hi, thanks for reporting this. I wonder how nobody has noticed that the color picker isn't working for over 1.5 years :D Do you need to change the color? Or you found this by accident?

**Comment by cmitz** [comment]
I was messing with my awesome, newly found chrome extension. :D
The error was fired on page load by the way.

Haha, that's it? Updated the software?
