### ISSUE TITLE
updating for e10s electrolysis in firefox?

### ISSUE THREAD

**Issue by jtwill** [jeremejevs/trimless-gmail#33]
Is there any chance this great utility can be updated for e10s electrolysis compatibility with firefox?

The current version gives a lot of "unsafe CPOW usage" warnings in the browser console, indicating that it is doing something that can cause trouble with e10s.

**Comment by jeremejevs** [comment]
Hi, thanks for reporting! Yeah, I've been warned about this by Mozilla, just didn't have time to react yet. Will do so now, hope it doesn't require too much change.

**Comment by frogworth** [comment]
No news on this, I guess?

**Comment by jeremejevs** [comment]
No, unfortunately. Sorry for empty promises. I do remember about this issue, but there are just so many other things to do...

**Comment by redion1992** [comment]
Given that 57 is now the stable version, is there any timeframe for an update expected? It is currently completely incompatible with stable Firefox, and by the end of June will be incompatible with the current ESR release.

**Comment by jeremejevs** [comment]
Sorry this took so long.

**Comment by jtwill** [comment]
Thank you! Works fine now!
