### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Xiamera** [jeremejevs/trimless-gmail#34]
Hi there,

I absolutely love this extension as most of my emails have been clipped by gmail for some time.  Unfortunately, a few days ago the extension seemed to stop working, and my emails are being clipped again.  Is there any reason this might be happening and/or is there a fix planned?

Thanks.

**Comment by jtwill** [comment]
Works for me with Firefox 58.0.2 on Windows.

What version of Firefox are you using?

**Comment by pitpar** [comment]
Now work in Versión 64.0.3282.186 (Build oficial) (64 bits), in previous version of Chrome don't works for me.

**Comment by pitpar** [comment]
Chrome, Versión 64.0.3282.186 (Build oficial) (64 bits), dont work for me, I'm back to 1.9.2

**Comment by jeremejevs** [comment]
I'm unable to reproduce this, neither in 64.0.3282.186 on Windows nor in 64.0.3282.167 on Linux.

Can you, please, confirm, that the untrimming is enabled? That is, the Trimless icon in the toolbar is red, when on a Gmail page:

![](https://i.imgur.com/c81E4Gm.png)

If it isn't, click it.

If the above doesn't help, right-click the toolbar icon and select "Options". In the options, click "Reset to defaults" and then "Save". Then go back to Gmail and see if the untrimming works, maybe try reloading the page.

Let me know how it goes. I have a tiny bit of faith in the options reset, since they appear to be non-default after installing the extension, however, they shouldn't affect the untrimming itself, regardless of how broken they are.

**Comment by Xiamera** [comment]
I've updated to the latest version of Chrome, and it's still not working. I ensured it was enabled, and I reset the options to the default.  Refreshed gmail, and it's still not working. I'll try deleting it and adding it again, to see if it works.

**Comment by Xiamera** [comment]
Deleted the extension, and re-enabled.  Still not working :(

**Comment by markevans567** [comment]
Starting a few days ago, the Trimless extension is also not working for me.
Although Trimless is installed and enabled, the icon is NOT red when viewing the Gmail inbox, or any individual message within Gmail.
I even uninstalled and reinstalled Trimless, making sure it is enabled.
MacOS 10.13.3
Chrome Version 64.0.3282.186 (Official Build) (64-bit) [up to date]
Trimless 1.10.0
Thank you for investigating!

**Comment by jeremejevs** [comment]
@Xiamera @markevans567 But have you guys left-clicked the gray scissors icon in the toolbar? That also enables/disables the extension.

**Comment by markevans567** [comment]
When I left-click or right-click on the toolbar icon, I see the following items:
1. Trimless for Google Mail (TM) -- opens Chrome web store page for extension
2. Options -- opens tab showing Extensions; on this tab, I can see the checkbox showing that Trimless is Enabled
3. Remove from Chrome...
4. Hide in Chrome menu
5. Manage Extensions -- opens tab showing Extensions; on this tab, I can see the checkbox showing that Trimless is Enabled
6. Inspect Popup (grayed out)
I do not see any menu item specifically for "enable" (or "disable").
And simply clicking on the icon has no effect; it doesn't enable or disable the extension, it just shows the menu items listed above.

**Comment by jeremejevs** [comment]
Can you try force-refreshing Gmail? `Cmd` + `Shift` + `R` on macOS. And then, if the scissors are still gray, try left-clicking them again. Just in case, this works only when viewing a Gmail tab, not any other page.

Also, can you verify that you aren't using a custom domain? That is, your URL starts with `https://mail.google.com/mail/`.

And if it still doesn't work, please, open the developer console on a Gmail tab (after the above-mentioned refresh), via `Cmd` + `Shift` + `J` on Mac, and make a screenshot of what's in there. Then click the dropdown where it says "top" and select "Trimless", and make a screenshot of that. Afterwards, go to `chrome://extensions/`, check the "Developer mode" checkbox on the top right, click "background page" below Trimless, and make a screenshot of the console that opens. Just in case, if the console is empty at any of the steps, you can skip making a screenshot. An empty console looks like this:

![](https://i.imgur.com/0k6vEZp.png)

And if you don't feel comfortable posting the screenshots publicly, you can send them to my email address, which you can find in my GitHub profile.

I have also found an unrelated bug and released `1.10.1`. I don't think it'll help, but who knows.

**Comment by markevans567** [comment]
Thanks.
Trimless was already updated to 1.10.1, that was quick! It didn't fix the problem, but maybe that update caused the scissors to turn red...?
Trimless is used on mail.google.com/mail.
I'll send you the screenshots -- more because of the number of them than because of privacy.
Thanks again.

**Comment by jeremejevs** [comment]
Thanks, @markevans567! Your screenshots have helped me pin down the bug. Upgraded the dependencies, when porting to the new Firefox, and used a slimmed down version of a helper library (jQuery), which happens to be missing the ability to make HTTP requests (XHR), and I was mistakenly convinced that it isn't needed. This is the time when one wishes they had regression tests.

`1.10.2` is up, please give it a go.

**Comment by markevans567** [comment]
Success! Thank you! I had to force-refresh Gmail, but once the refresh was complete, it worked perfectly. Well done, thank you again.

**Comment by Xiamera** [comment]
That fix worked for me as well!  Thank you so much for looking into this so quickly - and thank you to markevans for getting those screenshots up as well!

**Comment by jeremejevs** [comment]
Glad to hear! Thanks for reporting and helping in troubleshooting.
