### ISSUE TITLE
Trimless doesn't work with new GMail

### ISSUE THREAD

**Issue by ShellySachs** [jeremejevs/trimless-gmail#37]
It appears that Trimless is not working with the newly redesigned GMail. Please update soon!
Thanks,
Shelly

**Comment by ShellySachs** [comment]
Thanks.


Shelly Sachs
shelly@sachs3.com

**Comment by abelter** [comment]
It appears this is only affecting clipped messages; trimmed content (duplicate signatures, confidentiality notices, etc) are being handled as expected.

Google removed the "vem" class from the "View entire message" link and also placed that link into a separate div. I've tested the modified code below and it is working on both the old and new gmail UIs.

`	$("a:contains('View entire message')").each(function() {
		var tmpvem = $(this);
		$.get(this.href, function(data) {
			tmpvem.parents(".a3s").children("div:first").html($('font[size=-1]', data).last().html());
		});
	});`

**Comment by jeremejevs** [comment]
@abelter Do you wish to take a stab at this and open a PR? I'm still nowhere near having free time.

**Comment by ICDeadPpl** [comment]
@abelter Which line is the edit supposed to be at?

**Comment by abelter** [comment]
@jeremejevs My change is causing it to repeatedly reload the clipped content. Once I get past that I'll open a PR.

@ICDeadPpl Lines 58-63 of contentScript.js

**Comment by kesslink** [comment]
You can enable the new gmail interface on your legacy GSuite now. You need to do it from the admin-->GsuiteApps-->gmail screen. Then a new option will appear in your settings dropdown within gmail. 

Your Chrome add-on is one of the most valuable time (and annoyance) savers I've ever seen. I hope you find a bit of time to update it soon.

Thank you!

**Comment by ajakowenko** [comment]
New Gmail is rolling out to everyone next month (July) so coming soon, this awesome extension will no longer work for anyone =(. I would seriously pay for this extension if it could get updated for new Gmail.

**Comment by mcgwiz** [comment]
The instructions [here](https://productforums.google.com/forum/#!topic/gmail/lj6XmdKahgU) allowed me to successfully access the new Gmail while staying on a Legacy Free account.

**Comment by jeremejevs** [comment]
I've decided to stop maintaining this extension, sorry.

This task has been sitting in my todo list for ages now, and every time I think about it, I realize that it simply isn't worth it to me. I haven't used this extension for several years, and I'm on Inbox instead of Gmail, since the new design is too much of a disappointment to tolerate.

I'm happy to review PRs and do the publishing. Just no actual coding, thinking or thorough testing.

**Comment by ajakowenko** [comment]
Is your mind changed any knowing that they're shutting down Inbox?

**Comment by ICDeadPpl** [comment]
OT
Here's some tips how to make Gmail more pleasant: https://www.computerworld.com/article/3305068/email/gmail-desktop-interface.html

**Comment by Hawkeye56** [comment]
As of 8 October this is still affecting the new GMail and it is not possible to revert to the old version of GMail (would that it were!).

**Comment by ICDeadPpl** [comment]
Is there a way to make this a userscript for Greasemonkey, Tampermonkey and the likes?

**Comment by jeremejevs** [comment]
It's possible, but requires quite a few changes. Somebody would need to put in the hours, at which point they might as well just fork or take over this repo.

**Comment by jeremejevs** [comment]
The fix is available in 1.10.4. Please, report here if you see any untrimmed "View entire message".

**Comment by ShellySachs** [comment]
Works perfectly. Brilliant!

**Comment by FortFun** [comment]
Only works sometimes for me.

**Comment by jeremejevs** [comment]
@FortFun That must be a different problem then. Please, elaborate in a new issue.
