### ISSUE TITLE
trimmed content in pop out email reply window

### ISSUE THREAD

**Issue by bmahoney59** [jeremejevs/trimless-gmail#40]
Hi-
I'm hoping to automatically show trimmed content in the pop-out gmail reply window.  Was hoping this extension would do that.  If it is supposed to do that, would you have any suggestions for how I could get it to work?  I'm on the Brave Version 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit).  Thanks.

-Brian

**Comment by jeremejevs** [comment]
Hey Brian, Trimless wasn't supposed to do this, but I've looked into it and it was easy enough to add, so I just went ahead and did that. Once you have version 1.11.0, go into extension's options and enable it.

https://github.com/jeremejevs/trimless-gmail/commit/240ddb7646494148bec4c17b6f86c3b766b30bec

**Comment by bmahoney59** [comment]
Hey, Oleg-

I installed 1.11.0, but it still doesn't get the text from previous notes to appear automatically when I respond using the pop-out window (still need to press the ellipsis button at the bottom of the page to get it to show).  Thanks. for trying, though.  Much appreciated.

-Brian

**Comment by jeremejevs** [comment]
Have you enabled the feature though? It's opt-in:

![image](https://user-images.githubusercontent.com/2584727/58507721-0aa4d780-819b-11e9-9a42-fc269f2e73a2.png)

**Comment by bmahoney59** [comment]
Ahhhhhh.  There we go.  Thanks for the hand holding, Oleg.  This is awesome!  Just what I'd spent about two hours the other day trying to figure out how to do.  Thanks!

-Brian

**Comment by bmahoney59** [comment]
Hi, Oleg-

Sorry, I think that fix may have created a bug.  When I have the "untrim replies" box selected and go back to my inbox, then hit compose (new message, not reply) I'm getting some weird stuff with cursor placement.  When I first type in the body of the message, it's fine.  When I click to move the cursor into the subject field, the typing I do  continues to appear in the body of the note.  Turn off the extension and it works fine, text appears as normal.  Turn it back on and cursor weirdness comes back. 

I haven't tried to duplicate, but I've also seen a condition where I'm typing into the body and with a few carriage returns, nothing appears in the body or anywhere else that's visible.


-Brian

**Comment by jeremejevs** [comment]
Thanks for reporting the issue! Fixed and deployed with 1.11.1.

https://github.com/jeremejevs/trimless-gmail/commit/1c455cf369ac9ebddde8881242fd4ed08ebb0afe

**Comment by bmahoney59** [comment]
Cool, that fixed the cursor problem.  Now, though, it doesn't show the trimmed text when I reply in a pop-out window anymore (and I do have "untrim replies" checked in the settings).

**Comment by jeremejevs** [comment]
I cannot reproduce that, sorry. How do you initiate a pop-out reply? Do you press "Reply" in the regular view, then "Type of response" and then "Pop out reply"? Or some other way? And have you tried reloading Gmail?

**Comment by bmahoney59** [comment]
Yeah, sorry, I meant to tell you, Oleg.  It worked fine the next day.  I don't know what changed, but it works perfectly now.  Thanks for the change and the followup.  Much appreciated!

-Brian

**Comment by jeremejevs** [comment]
Hey Brian, glad to hear it's working now :slightly_smiling_face: Thanks for getting back to me about this!
