### ISSUE TITLE
Stopped working again in chrome

### ISSUE THREAD

**Issue by ShellySachs** [jeremejevs/trimless-gmail#41]
Here is the error message:

Unrecognized manifest key applications

{
   "applications": {
      "gecko": {
         "id": "trimless@jeremejevs.com"
      }
   },
   "background": {
      "persistent": false,
      "scripts": [ "vendor/tinycolor-1.4.1.min.js", "background.js" ]
   },
   "content_scripts": [ {
      "js": [ "vendor/jquery-3.3.1.min.js", "contentScript.js" ],
      "matches": [ "https://mail.google.com/mail/*" ],
      "run_at": "document_start"
   } ],
   "description": "Automatically shows trimmed content in Google Mail™.",
   "icons": {
      "128": "images/icon-128.png",
      "16": "images/icon-16.png",
      "48": "images/icon-48.png"
   },
   "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCq2+Jg/3mM/9KELc+n31TgvoSp1eTiLcOtgKMGqf9PQsPKcKBN6EFib8ZN8wQuvtdOiFdxuooiR+17yMsWUU/wxp8pu2tyyb611MirNFQTd5jdw6GjEz+nFPvJ9ik4Vs1Xnxi9sohd4Eo5hIiThfQWu9DffUXlS7WYSesURa70oQIDAQAB",
   "manifest_version": 2,
   "name": "Trimless for Google Mail™",
   "options_ui": {
      "chrome_style": true,
      "page": "options.html"
   },
   "page_action": {
      "default_icon": {
         "19": "images/icon-action-19.png",
         "38": "images/icon-action-38.png"
      },
      "default_title": "Trimless"
   },
   "permissions": [ "storage" ],
   "short_name": "Trimless Gmail",
   "update_url": "https://clients2.google.com/service/update2/crx",
   "version": "1.11.1"
}

**Comment by jeremejevs** [comment]
Sorry, can't reproduce. I have Chromium 75.0.3770.90 and it's working fine, installed as usual from the store. This error in particular isn't an error, but rather a warning, and shouldn't prevent the extension from working. Where do you see it? And how did this happen, when opening your browser after an update or something of that sort? What's the version of your Chrome?

**Comment by ShellySachs** [comment]
Using  75.0.3770.90 (Official Build) (32-bit). It was working absolutely
fine until a couple of days ago. The first time it happened, I clicked to
update the app, restarted the browser, and it worked for the rest of the
session (or I didn't notice otherwise). But today, nothing. Tried
everything on two different machines.

The error message comes from the extension page (see screen shots). It
shows up when I click on "error".

Any ideas?

Regards,
Shelly

**Comment by jeremejevs** [comment]
Have you tried removing the extension, and installing it anew? This is a really bizarre issue. Do you have any other extensions? Are they working fine? And I don't see the screenshots, it's probably because Github won't display email attachments.

**Comment by ShellySachs** [comment]
I just removed and reinstalled. Still not working. Interestingly, Nimbus
Screenshot (another great extension) was also not working. I also removed
and reinstalled it. It is now functioning again. I posted the screenshots
to a DropBox folder (
https://www.dropbox.com/sh/awq7owlwneqyklf/AABVpR1lsMuODCDPUQaZqw_ka?dl=0).
You can access them that way.
Regards,
Shelly

**Comment by jeremejevs** [comment]
Thanks for the screenshots. "Unrecognized manifest key" is a warning, the other two are errors, but seem to be just symptoms of the fact that something is broken, not the cause. [This thread](https://github.com/igrigorik/videospeed/issues/339) makes me think that it may be a conflict with another extension you have. Can you, please, try disabling all the other extensions, restarting the browser, and checking whether the problem persists?

**Comment by ShellySachs** [comment]
Did that and located the offender: F.B.(FluffBusting)Purity 29.0.1.0 . Too
bad. The app keeps Facebook cleaner and ad free. I will let that developer
know about the conflict.
Regards,
Shelly

**Comment by jeremejevs** [comment]
I see, thanks for testing. Has the developer responded?
